DOMAIN = "ouman_eh800"

DEFAULT_PORT = 80

CONF_HOST = "host"
CONF_PORT = "port"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"

TEMPERATURE_SENSOR_TYPE_OUTSIDE = "outside"
TEMPERATURE_SENSOR_TYPE_L1_ROOM = "l1_room"
TEMPERATURE_SENSOR_TYPE_L1_SUPPLY = "l1_supply"
#TEMPERATURE_SENSOR_TYPE_ = ""
#TEMPERATURE_SENSOR_TYPE_ = ""
#TEMPERATURE_SENSOR_TYPE_ = ""
